def get_qc_prompt(text):
    report_prompt = (
        "You are an advanced quality control report extractor. Extract structured quality control details from the provided text "
        "and return a **valid JSON object** that strictly follows this schema. **Do not return extra text, explanations, or comments.**\n\n"
        "### **Schema:**\n"
        "{\n"
        "  \"product_name\": \"string\",\n"
        "  \"RAG\": \"string\",\n"
        "  \"expected_qty\": \"string\",\n"
        "  \"received_qty\": \"string\",\n"
        "  \"supplier_code\": \"string\",\n"
        "  \"supplier\": \"string\",\n"
        "  \"coo\": \"string\",\n"
        "  \"received_date\": \"YYYY-MM-DD HH:MM:SS\",\n"
        "  \"inspection_date\": \"YYYY-MM-DD HH:MM:SS\",\n"
        "  \"print_date\": \"YYYY-MM-DD\",\n"
        "  \"iss_pallet_id\": \"integer\",\n"
        "  \"supplier_pallet_id\": \"integer\",\n"
        "  \"customer_pallet_id\": \"integer\",\n"
        "  \"variety\": \"string\",\n"
        "  \"brand\": \"string\",\n"
        "  \"organic\": \"YES\" or \"NO\",\n"
        "  \"does_pallet_meet_spec\": \"YES\" or \"NO\",\n"
        "  \"end_customer\": \"string\",\n"
        "  \"harvest_date\": \"YYYY-MM-DD\",\n"
        "  \"dp\": \"string\",\n"
        "  \"total_defects\": \"integer\",\n"
        "  \"size_calibre\": \"integer\",\n"
        "  \"lot_number\": \"string\",\n"
        "  \"inspector\": \"string\",\n"
        "  \"estimated_yield\": \"string\",\n"
        "  \"defects_fruit_total\": \"integer\",\n"
        "  \"packs_with_defects\": \"integer\",\n"
        "  \"waste_tot\": \"integer\",\n"
        "  \"waste_fruit_total\": \"integer\",\n"
        "  \"packs_with_waste\": \"integer\",\n"
        "  \"minor_defects_tot\": \"integer\",\n"
        "  \"minor_fruit_total\": \"integer\",\n"
        "  \"major_defects_tot\": \"integer\",\n"
        "  \"major_fruit_total\": \"integer\",\n"
        "  \"packs_with_major\": \"integer\",\n"
        "  \"box_pack_weights\": \"string\",\n"
        "  \"weight_readings\": \"string\",\n"
        "  \"fruit_weights\": \"string\",\n"
        "  \"qa_comments\": \"string\",\n"
        "  \"packs_fruits_inspected_sample_size\": \"integer\",\n"
        "  \"boxes_inspected\": \"integer\"\n"
        "}\n\n"
        "### **Strict Extraction Rules:**\n"
        "- RAG will be the color eg: RED, GREEN, BLUE, AMBER etc... look a color from the text"
        "- Some fields would be empty if you find large space founwed with a `anyname :` then keep null"
        "- Extract values **exactly as they appear** in the text.\n"
        "- If a field is **missing**, return it as **null**.\n"
        "- Do **not** infer or add extra information.\n"
        "- Remove unnecessary spaces from extracted values.\n"
        "- Output must be **pure JSON** with **no explanations, notes, or formatting errors**.\n\n"
        "### **Page Text:**\n"
    )
    return f"{report_prompt}{text}"
